name: Build/test
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all}}
      c: ${{ steps.changes.outputs.c }}
      gen: ${{ steps.changes.outputs.gen }}
    steps:
      - name: checkout tree-sitter-scala
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Get changed files
        id: changes
        run: |
          echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
          echo "c=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.\(c\|h\)$' | xargs)" >> $GITHUB_OUTPUT
          # Generated C code
          echo "gen=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.\(c\)$' | grep -v 'src/scanner.c' | grep -v 'bindings/python/tree_sitter_scala/binding.c' | xargs)" >> $GITHUB_OUTPUT

  test:
    runs-on: ${{ matrix.os }}
    needs: changedfiles
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: checkout tree-sitter-scala
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: checkout scala/scala
        if: ${{ runner.os == 'Linux' }}
        uses: actions/checkout@v4
        with:
          repository: scala/scala
          ref: v2.13.14
          path: scala_scala

      - name: checkout scala/scala3
        if: ${{ runner.os == 'Linux' }}
        uses: actions/checkout@v4
        with:
          repository: scala/scala3
          ref: 3.5.0-RC2
          path: dotty

      - name: checkout lichess-org/lila
        if: ${{ runner.os == 'Linux' }}
        uses: actions/checkout@v4
        with:
          repository: lichess-org/lila
          ref: 83e61b9ef617164fe1d3a5112fcc611d0e5a7ea9
          path: lila

      - name: checkout nvim-treesitter/nvim-treesitter
        if: ${{ runner.os == 'Linux' }}
        uses: actions/checkout@v4
        with:
          repository: nvim-treesitter/nvim-treesitter
          path: nvim_treesitter

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
        with:
          tree-sitter-ref: v0.24.7

      - name: Generate parser from scratch and test it
        shell: bash
        run: tree-sitter generate

      - name: Run parser and binding tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
          test-rust: true
          test-node: true
          test-python: true
          test-go: true
          test-swift: false

      - name: Parse sample files
        uses: tree-sitter/parse-action@v4
        id: parse-files
        with:
          files: examples/**

      - name: Check fidelity of checked-in C code
        if: ${{ runner.os == 'Linux' && needs.changedfiles.outputs.gen }}
        shell: bash
        run: |
          # `git diff --quiet` doesn't seem to work on Github Actions
          changes=$(git diff --name-only --diff-filter=ACMRT | xargs)
          if [ ! -z "$changes" ]; then
            echo "::error file=grammar.js::Generated $changes differs from the checked in version"
            git diff --exit-code
            exit 1
          fi

      - name: Smoke test
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        env:
          SCALA_SCALA_DIR: scala_scala
          DOTTY_DIR: dotty
          LILA_DIR: lila
        run: script/smoke_test.sh

      - name: Check that prettier exists
        if: ${{ runner.os == 'Linux' }}
        run: |
          npm install
          export PATH=./node_modules/.bin:$PATH
          prettier --write --ignore-unknown grammar.js

      - name: copy nvim-treesitter queries
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: cp ./nvim_treesitter/queries/scala/*.scm ./queries/

      - name: Check if queries are out of sync with nvim-treesitter
        if: ${{ runner.os == 'Linux' }}
        uses: tj-actions/verify-changed-files@v19
        id: verify-changed-files
        with:
          files: |
            queries/*.scm

      # TODO: uncomment when this works
      # - name: Test quries if out of sync with nvim-treesitter
      #   if: steps.verify-changed-files.outputs.files_changed == 'true'
      #   run: |
      #     echo "::warning Queries in ${{ steps.verify-changed-files.outputs.changed_files }} in this repo are out of sync with nvim-treesitter"
      #     git diff queries/
      #     npm run test
