name: Build/test
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  changedfiles:
    runs-on: ubuntu-20.04
    outputs:
      all: ${{ steps.changes.outputs.all}}
      c: ${{ steps.changes.outputs.c }}
    steps:
      - name: checkout tree-sitter-scala
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: Get changed files
        id: changes
        run: |
          echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
          echo "c=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.\(c\|h\)$' | xargs)" >> $GITHUB_OUTPUT

  test:
    runs-on: ${{ matrix.os }}
    needs: changedfiles
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
    env:
      SCALA_SCALA_DIR: /Users/runner/work/tree-sitter-scala/tree-sitter-scala/scala_scala
      DOTTY_DIR: /Users/runner/work/tree-sitter-scala/tree-sitter-scala/dotty
    steps:
      - name: checkout tree-sitter-scala
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - name: checkout scala/scala
        if: ${{ runner.os == 'macOS' }}
        uses: actions/checkout@v3
        with:
          repository: scala/scala
          ref: v2.13.10
          path: scala_scala

      - name: checkout lampepfl/dotty
        if: ${{ runner.os == 'macOS' }}
        uses: actions/checkout@v3
        with:
          repository: lampepfl/dotty
          ref: 3.2.1
          path: dotty

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test C stack code
        run: gcc test/test-stack.c -o a.out && ./a.out

      - name: Generate parser
        if: ${{ runner.os == 'macOS' }}
        shell: bash
        run: |
          npm install
          npm run build
          npm test

      - name: Check parser (Linux)
        if: ${{ runner.os == 'macOS' && needs.changedfiles.outputs.c }}
        shell: bash
        run: |
          # `git diff --quiet` doesn't seem to work on Github Actions
          changes=$(git diff --name-only --diff-filter=ACMRT | xargs)
          if [ ! "$changes" ]; then
            echo "::error file=grammar.js::Generated parser differs from the checked in version"
            exit 1
          fi

      - name: Parser tests
        if: ${{ needs.changedfiles.outputs.c }}
        shell: bash
        run: npm install && npm test

      - name: Smoke test
        if: ${{ runner.os == 'macOS' }}
        shell: bash
        run: script/smoke_test.sh
