name: Publish packages

on:
  push:
    tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  github:
    uses: tree-sitter/workflows/.github/workflows/release.yml@9a10bab3d9bb66d2cc9283b65fad01ddca3ef62c
    with:
      generate: true
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@9a10bab3d9bb66d2cc9283b65fad01ddca3ef62c
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    with:
      generate: true
  crates:
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@9a10bab3d9bb66d2cc9283b65fad01ddca3ef62c
    secrets:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
    with:
      generate: true
  pypi:
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@9a10bab3d9bb66d2cc9283b65fad01ddca3ef62c
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
    with:
      generate: true
